# Generated by Django 5.0.14 on 2026-02-25 06:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AddConstraint(
            model_name='user',
            constraint=models.CheckConstraint(check=models.Q(models.Q(('agreed_to_upl_disclaimer', True), ('upl_disclaimer_agreed_at__isnull', False)), models.Q(('agreed_to_upl_disclaimer', False), ('upl_disclaimer_agreed_at__isnull', True)), _connector='OR'), name='upl_agreement_consistency'),
        ),
    ]
