# Generated by Django 5.0.14 on 2026-01-04 18:01

import django.db.models.deletion
import encrypted_model_fields.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("districts", "0002_alter_district_state_and_more"),
        ("intake", "__first__"),
    ]

    operations = [
        migrations.CreateModel(
            name="MeansTest",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "median_income_threshold",
                    models.DecimalField(
                        decimal_places=2,
                        help_text="Median income for family size",
                        max_digits=12,
                    ),
                ),
                (
                    "calculated_cmi",
                    models.DecimalField(
                        decimal_places=2,
                        help_text="Current Monthly Income",
                        max_digits=12,
                    ),
                ),
                (
                    "passes_means_test",
                    models.BooleanField(
                        db_index=True, help_text="True if CMI < median income"
                    ),
                ),
                (
                    "calculation_details",
                    encrypted_model_fields.fields.EncryptedTextField(
                        default="{}", help_text="Full calculation breakdown (JSON)"
                    ),
                ),
                ("qualifies_for_fee_waiver", models.BooleanField(default=False)),
                ("calculated_at", models.DateTimeField(auto_now_add=True)),
                (
                    "district",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        to="districts.district",
                    ),
                ),
                (
                    "session",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="means_test",
                        to="intake.intakesession",
                    ),
                ),
            ],
            options={
                "db_table": "means_tests",
            },
        ),
    ]
