# Generated by Django 5.0.14 on 2026-06-18 03:35

from decimal import Decimal

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("eligibility", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="meanstest",
            name="above_median_calculated",
            field=models.BooleanField(
                default=False, help_text="Whether above-median calculation was performed"
            ),
        ),
        migrations.AddField(
            model_name="meanstest",
            name="disposable_income",
            field=models.DecimalField(
                decimal_places=2,
                default=Decimal("0"),
                help_text="Monthly disposable income after deductions",
                max_digits=12,
            ),
        ),
        migrations.AddField(
            model_name="meanstest",
            name="passes_above_median",
            field=models.BooleanField(
                default=False, help_text="True if disposable income < $756.25/mo"
            ),
        ),
        migrations.AddField(
            model_name="meanstest",
            name="priority_debts_monthly",
            field=models.DecimalField(
                decimal_places=2,
                default=Decimal("0"),
                help_text="Monthly priority debt payments",
                max_digits=12,
            ),
        ),
        migrations.AddField(
            model_name="meanstest",
            name="total_allowable_expenses",
            field=models.DecimalField(
                decimal_places=2,
                default=Decimal("0"),
                help_text="Monthly allowable expenses (IRS standards + actual)",
                max_digits=12,
            ),
        ),
    ]
