# Generated by Django 5.0.14 on 2026-01-04 21:23

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("intake", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="GeneratedForm",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "form_type",
                    models.CharField(
                        choices=[
                            ("form_101", "Form 101 - Voluntary Petition"),
                            ("schedule_a_b", "Schedule A/B - Property"),
                            ("schedule_c", "Schedule C - Exemptions"),
                            ("schedule_d", "Schedule D - Secured Creditors"),
                            ("schedule_e_f", "Schedule E/F - Unsecured Creditors"),
                            ("schedule_i", "Schedule I - Income"),
                            ("schedule_j", "Schedule J - Expenses"),
                            (
                                "means_test",
                                "Statement of Current Monthly Income (Means Test)",
                            ),
                        ],
                        help_text="Type of bankruptcy form",
                        max_length=20,
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("draft", "Draft"),
                            ("generated", "Generated"),
                            ("downloaded", "Downloaded"),
                            ("filed", "Filed with Court"),
                        ],
                        default="draft",
                        help_text="Current status of the form",
                        max_length=20,
                    ),
                ),
                (
                    "form_data",
                    models.JSONField(
                        help_text="Populated form field data ready for PDF generation"
                    ),
                ),
                (
                    "pdf_file_path",
                    models.CharField(
                        blank=True,
                        help_text="Path to generated PDF file",
                        max_length=255,
                    ),
                ),
                (
                    "generated_at",
                    models.DateTimeField(
                        auto_now_add=True, help_text="When the form was generated"
                    ),
                ),
                (
                    "updated_at",
                    models.DateTimeField(
                        auto_now=True, help_text="Last update timestamp"
                    ),
                ),
                (
                    "generated_by",
                    models.ForeignKey(
                        help_text="User who generated this form",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "session",
                    models.ForeignKey(
                        help_text="Intake session this form belongs to",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="generated_forms",
                        to="intake.intakesession",
                    ),
                ),
            ],
            options={
                "db_table": "generated_forms",
                "ordering": ["-generated_at"],
                "unique_together": {("session", "form_type")},
            },
        ),
    ]
