# Generated by Django 5.0.14 on 2026-06-17 00:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("forms", "0002_add_missing_form_types"),
    ]

    operations = [
        migrations.AddField(
            model_name="generatedform",
            name="template_version",
            field=models.CharField(
                blank=True,
                default="",
                help_text="Schema/template version hash this form was filled against (reproducibility)",
                max_length=64,
            ),
        ),
    ]
