# Generated by Django 5.0.14 on 2026-06-18 01:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("forms", "0003_generatedform_template_version"),
    ]

    operations = [
        migrations.AlterField(
            model_name="generatedform",
            name="form_type",
            field=models.CharField(
                choices=[
                    ("form_101", "Form 101 - Voluntary Petition"),
                    ("form_103b", "Form 103B - Fee Waiver Application"),
                    ("form_106dec", "Form 106Dec - Declaration"),
                    ("form_106sum", "Form 106Sum - Summary of Assets/Liabilities"),
                    ("form_107", "Form 107 - Statement of Financial Affairs"),
                    ("form_121", "Form 121 - SSN Statement"),
                    ("form_122a1", "Form 122A-1 - Means Test"),
                    ("form_122a1_supp", "Form 122A-1 Supplement"),
                    ("form_122a2", "Form 122A-2 - Means Test Calculation"),
                    ("form_122b", "Form 122B - Alternative Means Test"),
                    ("schedule_a_b", "Schedule A/B - Property"),
                    ("schedule_c", "Schedule C - Exemptions"),
                    ("schedule_d", "Schedule D - Secured Creditors"),
                    ("schedule_e_f", "Schedule E/F - Unsecured Creditors"),
                    ("schedule_g", "Schedule G - Executory Contracts/Leases"),
                    ("schedule_h", "Schedule H - Codebtors"),
                    ("schedule_i", "Schedule I - Income"),
                    ("schedule_j", "Schedule J - Expenses"),
                ],
                help_text="Type of bankruptcy form",
                max_length=20,
            ),
        ),
    ]
