# Generated by Django 5.0.14 on 2026-01-04 05:30

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='District',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(help_text="District code, e.g., 'ilnd'.", max_length=8, unique=True)),
                ('name', models.CharField(help_text='Full name of the district.', max_length=128)),
                ('state', models.CharField(db_index=True, help_text='Two-letter state abbreviation.', max_length=2)),
                ('court_name', models.CharField(help_text='Official name of the bankruptcy court.', max_length=128)),
                ('pro_se_efiling_allowed', models.BooleanField(default=False, help_text='Is pro se E-filing allowed?')),
                ('filing_fee_chapter_7', models.DecimalField(decimal_places=2, help_text='Chapter 7 filing fee (USD).', max_digits=10)),
                ('created_at', models.DateTimeField(auto_now_add=True, help_text='Record creation time.')),
                ('updated_at', models.DateTimeField(auto_now=True, help_text='Record update time.')),
            ],
            options={
                'verbose_name': 'District',
                'verbose_name_plural': 'Districts',
                'ordering': ['state', 'name'],
            },
        ),
        migrations.CreateModel(
            name='ExemptionSchedule',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('exemption_type', models.CharField(choices=[('homestead', 'Homestead'), ('vehicle', 'Vehicle'), ('tools_of_trade', 'Tools of Trade'), ('wildcard', 'Wildcard')], help_text='Type of exemption.', max_length=16)),
                ('amount', models.DecimalField(decimal_places=2, help_text='Maximum exemption amount (USD).', max_digits=12)),
                ('statute_citation', models.CharField(help_text='Legal citation for this exemption.', max_length=64)),
                ('description', models.TextField(help_text='Plain language description of the exemption.')),
                ('created_at', models.DateTimeField(auto_now_add=True, help_text='Record creation time.')),
                ('district', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='exemption_schedules', to='districts.district')),
            ],
            options={
                'verbose_name': 'Exemption Schedule',
                'verbose_name_plural': 'Exemption Schedules',
                'ordering': ['district', 'exemption_type'],
                'unique_together': {('district', 'exemption_type', 'statute_citation')},
            },
        ),
        migrations.CreateModel(
            name='LocalRule',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rule_number', models.CharField(help_text='Local rule number or identifier.', max_length=16)),
                ('title', models.CharField(help_text='Short title of the rule.', max_length=128)),
                ('description', models.TextField(help_text='Full description or requirements under the rule.')),
                ('effective_date', models.DateField(help_text='Date when this rule became effective.')),
                ('created_at', models.DateTimeField(auto_now_add=True, help_text='Record creation time.')),
                ('district', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='local_rules', to='districts.district')),
            ],
            options={
                'verbose_name': 'Local Rule',
                'verbose_name_plural': 'Local Rules',
                'ordering': ['district', 'rule_number'],
                'unique_together': {('district', 'rule_number', 'effective_date')},
            },
        ),
        migrations.CreateModel(
            name='MedianIncome',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('effective_date', models.DateField(help_text='Date when this median income threshold became effective.')),
                ('family_size_1', models.DecimalField(decimal_places=2, help_text='1-person household median income.', max_digits=12)),
                ('family_size_2', models.DecimalField(decimal_places=2, help_text='2-person household median income.', max_digits=12)),
                ('family_size_3', models.DecimalField(decimal_places=2, help_text='3-person household median income.', max_digits=12)),
                ('family_size_4', models.DecimalField(decimal_places=2, help_text='4-person household median income.', max_digits=12)),
                ('family_size_5', models.DecimalField(decimal_places=2, help_text='5-person household median income.', max_digits=12)),
                ('family_size_6', models.DecimalField(decimal_places=2, help_text='6-person household median income.', max_digits=12)),
                ('family_size_7', models.DecimalField(decimal_places=2, help_text='7-person household median income.', max_digits=12)),
                ('family_size_8', models.DecimalField(decimal_places=2, help_text='8-person household median income.', max_digits=12)),
                ('family_size_additional', models.DecimalField(blank=True, decimal_places=2, default=9900.0, help_text='Amount to add for each additional person above 8.', max_digits=12, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True, help_text='Record creation time.')),
                ('district', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='median_incomes', to='districts.district')),
            ],
            options={
                'verbose_name': 'Median Income',
                'verbose_name_plural': 'Median Incomes',
                'ordering': ['-effective_date', 'district'],
                'unique_together': {('district', 'effective_date')},
            },
        ),
    ]
