# Generated by Django 5.0.14 on 2026-02-02

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone
import django_fernet_fields.fields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('intake', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='UploadedDocument',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('document_type', models.CharField(choices=[('pay_stub', 'Pay Stub'), ('bank_statement', 'Bank Statement'), ('credit_cert', 'Credit Counseling Certificate'), ('credit_report', 'Credit Report'), ('tax_return_personal', 'Personal Tax Return (1040)'), ('special_circumstances', 'Supporting Document'), ('balance_sheet', 'Balance Sheet'), ('profit_loss', 'Profit & Loss Statement'), ('cash_flow', 'Cash Flow Statement'), ('tax_return_business', 'Business Tax Return'), ('accounts_receivable', 'Accounts Receivable Aging'), ('accounts_payable', 'Accounts Payable Aging'), ('operating_agreement', 'Operating Agreement'), ('corporate_resolution', 'Corporate Resolution'), ('lease_agreement', 'Lease Agreement'), ('loan_agreement', 'Loan Agreement'), ('judgment', 'Court Judgment'), ('lien_notice', 'Lien Notice')], help_text='Final document type (after validation)', max_length=50)),
                ('user_declared_type', models.CharField(choices=[('pay_stub', 'Pay Stub'), ('bank_statement', 'Bank Statement'), ('credit_cert', 'Credit Counseling Certificate'), ('credit_report', 'Credit Report'), ('tax_return_personal', 'Personal Tax Return (1040)'), ('special_circumstances', 'Supporting Document'), ('balance_sheet', 'Balance Sheet'), ('profit_loss', 'Profit & Loss Statement'), ('cash_flow', 'Cash Flow Statement'), ('tax_return_business', 'Business Tax Return'), ('accounts_receivable', 'Accounts Receivable Aging'), ('accounts_payable', 'Accounts Payable Aging'), ('operating_agreement', 'Operating Agreement'), ('corporate_resolution', 'Corporate Resolution'), ('lease_agreement', 'Lease Agreement'), ('loan_agreement', 'Loan Agreement'), ('judgment', 'Court Judgment'), ('lien_notice', 'Lien Notice')], help_text='Type user selected before upload', max_length=50)),
                ('detected_type', models.CharField(blank=True, choices=[('pay_stub', 'Pay Stub'), ('bank_statement', 'Bank Statement'), ('credit_cert', 'Credit Counseling Certificate'), ('credit_report', 'Credit Report'), ('tax_return_personal', 'Personal Tax Return (1040)'), ('special_circumstances', 'Supporting Document'), ('balance_sheet', 'Balance Sheet'), ('profit_loss', 'Profit & Loss Statement'), ('cash_flow', 'Cash Flow Statement'), ('tax_return_business', 'Business Tax Return'), ('accounts_receivable', 'Accounts Receivable Aging'), ('accounts_payable', 'Accounts Payable Aging'), ('operating_agreement', 'Operating Agreement'), ('corporate_resolution', 'Corporate Resolution'), ('lease_agreement', 'Lease Agreement'), ('loan_agreement', 'Loan Agreement'), ('judgment', 'Court Judgment'), ('lien_notice', 'Lien Notice')], help_text='Type detected by OCR (for validation)', max_length=50, null=True)),
                ('file', django_fernet_fields.fields.EncryptedFileField(upload_to='documents/%Y/%m/')),
                ('original_filename', models.CharField(max_length=255)),
                ('file_size', models.IntegerField(help_text='Size in bytes')),
                ('mime_type', models.CharField(max_length=100)),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
                ('delete_after', models.DateTimeField(help_text='Auto-delete after 22 days or form filing')),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('session', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='uploaded_documents', to='intake.intakesession')),
                ('uploaded_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='uploaded_documents', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'uploaded_documents',
                'ordering': ['-uploaded_at'],
            },
        ),
        migrations.CreateModel(
            name='OCRResult',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('processing', 'Processing'), ('completed', 'Completed'), ('failed', 'Failed'), ('validated', 'Validated by User')], default='pending', max_length=20)),
                ('ocr_provider', models.CharField(default='clarifai', help_text='OCR provider used (clarifai or vllm)', max_length=50)),
                ('extracted_data', models.TextField(help_text='JSON structure of extracted fields')),
                ('confidence_scores', models.JSONField(default=dict, help_text='Per-field confidence scores (0-100)')),
                ('overall_confidence', models.DecimalField(decimal_places=2, help_text='Overall confidence score (0-100)', max_digits=5)),
                ('user_validated', models.BooleanField(default=False)),
                ('validation_changes', models.JSONField(default=list, help_text='List of fields user corrected after extraction')),
                ('processed_at', models.DateTimeField(auto_now_add=True)),
                ('processing_duration', models.FloatField(help_text='Seconds to process', null=True)),
                ('error_message', models.TextField(blank=True, null=True)),
                ('document', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='ocr_result', to='documents.uploadeddocument')),
            ],
            options={
                'db_table': 'ocr_results',
                'ordering': ['-processed_at'],
            },
        ),
        migrations.AddIndex(
            model_name='uploadeddocument',
            index=models.Index(fields=['session', 'document_type'], name='uploaded_do_session_c64b40_idx'),
        ),
        migrations.AddIndex(
            model_name='uploadeddocument',
            index=models.Index(fields=['delete_after'], name='uploaded_do_delete__a50ed2_idx'),
        ),
    ]
