# Generated by Django 5.0.14 on 2026-05-16 05:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("documents", "0001_initial"),
    ]

    operations = [
        migrations.RenameIndex(
            model_name="uploadeddocument",
            new_name="uploaded_do_session_b0c44c_idx",
            old_name="uploaded_do_session_c64b40_idx",
        ),
        migrations.RenameIndex(
            model_name="uploadeddocument",
            new_name="uploaded_do_delete__00d040_idx",
            old_name="uploaded_do_delete__a50ed2_idx",
        ),
        migrations.AlterField(
            model_name="uploadeddocument",
            name="detected_type",
            field=models.CharField(
                blank=True,
                choices=[
                    ("pay_stub", "Pay Stub"),
                    ("bank_statement", "Bank Statement"),
                    ("credit_cert", "Credit Counseling Certificate"),
                    ("credit_report", "Credit Report"),
                    ("tax_return_personal", "Personal Tax Return (1040)"),
                    ("special_circumstances", "Supporting Document"),
                    ("balance_sheet", "Balance Sheet"),
                    ("profit_loss", "Profit & Loss Statement"),
                    ("cash_flow", "Cash Flow Statement"),
                    ("tax_return_business", "Business Tax Return"),
                    ("accounts_receivable", "Accounts Receivable Aging"),
                    ("accounts_payable", "Accounts Payable Aging"),
                    ("operating_agreement", "Operating Agreement"),
                    ("corporate_resolution", "Corporate Resolution"),
                    ("lease_agreement", "Lease Agreement"),
                    ("loan_agreement", "Loan Agreement"),
                    ("judgment", "Court Judgment"),
                    ("lien_notice", "Lien Notice"),
                    ("creditor_bill", "Creditor Bill / Statement"),
                ],
                help_text="Type detected by OCR (for validation)",
                max_length=50,
                null=True,
            ),
        ),
        migrations.AlterField(
            model_name="uploadeddocument",
            name="document_type",
            field=models.CharField(
                choices=[
                    ("pay_stub", "Pay Stub"),
                    ("bank_statement", "Bank Statement"),
                    ("credit_cert", "Credit Counseling Certificate"),
                    ("credit_report", "Credit Report"),
                    ("tax_return_personal", "Personal Tax Return (1040)"),
                    ("special_circumstances", "Supporting Document"),
                    ("balance_sheet", "Balance Sheet"),
                    ("profit_loss", "Profit & Loss Statement"),
                    ("cash_flow", "Cash Flow Statement"),
                    ("tax_return_business", "Business Tax Return"),
                    ("accounts_receivable", "Accounts Receivable Aging"),
                    ("accounts_payable", "Accounts Payable Aging"),
                    ("operating_agreement", "Operating Agreement"),
                    ("corporate_resolution", "Corporate Resolution"),
                    ("lease_agreement", "Lease Agreement"),
                    ("loan_agreement", "Loan Agreement"),
                    ("judgment", "Court Judgment"),
                    ("lien_notice", "Lien Notice"),
                    ("creditor_bill", "Creditor Bill / Statement"),
                ],
                help_text="Final document type (after validation)",
                max_length=50,
            ),
        ),
        migrations.AlterField(
            model_name="uploadeddocument",
            name="user_declared_type",
            field=models.CharField(
                choices=[
                    ("pay_stub", "Pay Stub"),
                    ("bank_statement", "Bank Statement"),
                    ("credit_cert", "Credit Counseling Certificate"),
                    ("credit_report", "Credit Report"),
                    ("tax_return_personal", "Personal Tax Return (1040)"),
                    ("special_circumstances", "Supporting Document"),
                    ("balance_sheet", "Balance Sheet"),
                    ("profit_loss", "Profit & Loss Statement"),
                    ("cash_flow", "Cash Flow Statement"),
                    ("tax_return_business", "Business Tax Return"),
                    ("accounts_receivable", "Accounts Receivable Aging"),
                    ("accounts_payable", "Accounts Payable Aging"),
                    ("operating_agreement", "Operating Agreement"),
                    ("corporate_resolution", "Corporate Resolution"),
                    ("lease_agreement", "Lease Agreement"),
                    ("loan_agreement", "Loan Agreement"),
                    ("judgment", "Court Judgment"),
                    ("lien_notice", "Lien Notice"),
                    ("creditor_bill", "Creditor Bill / Statement"),
                ],
                help_text="Type user selected before upload",
                max_length=50,
            ),
        ),
    ]
