# Generated by Django 5.0.14 on 2026-06-17 18:24

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("documents", "0002_documenttype_creditor_bill"),
        ("intake", "0008_sofa_report_default_fix"),
    ]

    operations = [
        migrations.CreateModel(
            name="IngestedAggregate",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                ("ingest_key", models.CharField(max_length=100)),
                ("value", models.CharField(max_length=255)),
                (
                    "session",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="ingested_aggregates",
                        to="intake.intakesession",
                    ),
                ),
            ],
            options={
                "db_table": "ingested_aggregates",
                "unique_together": {("session", "ingest_key")},
            },
        ),
    ]
