# Generated by Django 5.0.14 on 2026-06-21 22:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("documents", "0003_ingestedaggregate"),
    ]

    operations = [
        migrations.AlterField(
            model_name="ocrresult",
            name="ocr_provider",
            field=models.CharField(default="gemini", help_text="OCR provider used", max_length=50),
        ),
    ]
