# Generated by Django 5.0.14 on 2026-07-23 18:54

import encrypted_model_fields.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("documents", "0004_alter_ocrresult_ocr_provider"),
    ]

    operations = [
        migrations.AlterField(
            model_name="ocrresult",
            name="extracted_data",
            field=encrypted_model_fields.fields.EncryptedTextField(
                help_text="Encrypted JSON of extracted fields"
            ),
        ),
    ]
