# Generated by Django 5.0.14 on 2026-01-04 20:11

import apps.intake.fields
import django.db.models.deletion
import encrypted_model_fields.fields
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('districts', '0002_alter_district_state_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='IntakeSession',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('started', 'Started'), ('in_progress', 'In Progress'), ('completed', 'Completed'), ('abandoned', 'Abandoned')], default='started', max_length=20)),
                ('current_step', models.IntegerField(default=1)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('district', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='districts.district')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='intake_sessions', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'intake_sessions',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='IncomeInfo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('marital_status', models.CharField(choices=[('single', 'Single'), ('married_joint', 'Married Filing Jointly'), ('married_separate', 'Married Filing Separately')], max_length=30)),
                ('number_of_dependents', models.IntegerField(default=0)),
                ('monthly_income', models.JSONField(help_text='6-month income array')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('session', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='income_info', to='intake.intakesession')),
            ],
            options={
                'db_table': 'income_info',
            },
        ),
        migrations.CreateModel(
            name='ExpenseInfo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data_source', models.CharField(choices=[('manual', 'Manually Entered'), ('plaid', 'Plaid API'), ('uploaded_document', 'Uploaded Document')], default='manual', help_text='Source of expense data for audit trail', max_length=30)),
                ('rent_or_mortgage', models.DecimalField(decimal_places=2, default=0, help_text='Monthly housing payment', max_digits=10)),
                ('utilities', models.DecimalField(decimal_places=2, default=0, help_text='Gas, electric, water, etc.', max_digits=10)),
                ('home_maintenance', models.DecimalField(decimal_places=2, default=0, help_text='Repairs and upkeep', max_digits=10)),
                ('vehicle_payment', models.DecimalField(decimal_places=2, default=0, help_text='Car loan or lease payment', max_digits=10)),
                ('vehicle_insurance', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('vehicle_maintenance', models.DecimalField(decimal_places=2, default=0, help_text='Gas, repairs, registration', max_digits=10)),
                ('food_and_groceries', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('clothing', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('medical_expenses', models.DecimalField(decimal_places=2, default=0, help_text='Out-of-pocket healthcare costs', max_digits=10)),
                ('childcare', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('child_support_paid', models.DecimalField(decimal_places=2, default=0, help_text='Court-ordered support payments', max_digits=10)),
                ('insurance_not_deducted', models.DecimalField(decimal_places=2, default=0, help_text='Health, life, or disability insurance not deducted from paycheck', max_digits=10)),
                ('other_expenses', models.DecimalField(decimal_places=2, default=0, help_text='Other necessary monthly expenses', max_digits=10)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('session', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='expense_info', to='intake.intakesession')),
            ],
            options={
                'db_table': 'expense_info',
            },
        ),
        migrations.CreateModel(
            name='DebtorInfo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=100)),
                ('last_name', models.CharField(max_length=100)),
                ('middle_name', models.CharField(blank=True, max_length=100)),
                ('ssn', encrypted_model_fields.fields.EncryptedCharField()),
                ('date_of_birth', models.DateField()),
                ('phone', models.CharField(max_length=15)),
                ('email', models.EmailField(max_length=254)),
                ('street_address', models.CharField(max_length=255)),
                ('city', models.CharField(max_length=100)),
                ('state', models.CharField(max_length=2)),
                ('zip_code', models.CharField(max_length=10)),
                ('session', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='debtor_info', to='intake.intakesession')),
            ],
            options={
                'db_table': 'debtor_info',
            },
        ),
        migrations.CreateModel(
            name='DebtInfo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data_source', models.CharField(choices=[('manual', 'Manually Entered'), ('credit_report', 'Credit Report'), ('uploaded_document', 'Uploaded Document')], default='manual', help_text='Source of creditor data for audit trail', max_length=30)),
                ('creditor_name', models.CharField(help_text='Name of creditor or collection agency', max_length=255)),
                ('debt_type', models.CharField(choices=[('credit_card', 'Credit Card'), ('medical', 'Medical Bill'), ('personal_loan', 'Personal Loan'), ('student_loan', 'Student Loan'), ('auto_loan', 'Auto Loan'), ('mortgage', 'Mortgage/Home Loan'), ('utility', 'Utility Bill'), ('other', 'Other Amount Owed')], max_length=30)),
                ('priority_classification', models.CharField(choices=[('unsecured', 'Unsecured (Credit Card, Medical)'), ('secured', 'Secured (Car Loan, Mortgage)'), ('priority', 'Priority (Taxes, Child Support)')], default='unsecured', help_text='Legal classification for bankruptcy filing', max_length=30)),
                ('account_number', encrypted_model_fields.fields.EncryptedCharField(blank=True, help_text='Last 4 digits or full account number (encrypted)')),
                ('amount_owed', apps.intake.fields.EncryptedDecimalField(decimal_places=2, help_text="Current balance (trauma-informed: 'amount owed' vs 'debt')", max_digits=12)),
                ('monthly_payment', models.DecimalField(blank=True, decimal_places=2, help_text='Minimum monthly payment if still paying', max_digits=10, null=True)),
                ('is_in_collections', models.BooleanField(default=False, help_text='Has this account been sent to collections?')),
                ('notes', models.TextField(blank=True, help_text='Additional context about this amount owed')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('session', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='debts', to='intake.intakesession')),
            ],
            options={
                'db_table': 'debt_info',
                'ordering': ['priority_classification', '-amount_owed'],
            },
        ),
        migrations.CreateModel(
            name='AssetInfo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('asset_type', models.CharField(choices=[('real_property', 'Real Estate/Home'), ('vehicle', 'Vehicle'), ('bank_account', 'Bank Account'), ('retirement_account', 'Retirement Account (401k, IRA)'), ('other', 'Other Asset')], max_length=30)),
                ('data_source', models.CharField(choices=[('manual', 'Manually Entered'), ('plaid', 'Plaid API'), ('uploaded_document', 'Uploaded Document')], default='manual', help_text='Source of asset data for audit trail', max_length=30)),
                ('description', models.CharField(help_text="Brief description (e.g., '2015 Honda Civic', '123 Main St')", max_length=255)),
                ('current_value', apps.intake.fields.EncryptedDecimalField(decimal_places=2, help_text='Current fair market value', max_digits=12)),
                ('amount_owed', apps.intake.fields.EncryptedDecimalField(decimal_places=2, default=0, help_text='Outstanding loan or lien amount', max_digits=12)),
                ('account_number', encrypted_model_fields.fields.EncryptedCharField(blank=True, help_text='Last 4 digits or full account number (encrypted)')),
                ('financial_institution', models.CharField(blank=True, help_text='Bank or institution name', max_length=100)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('session', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='assets', to='intake.intakesession')),
            ],
            options={
                'db_table': 'asset_info',
                'ordering': ['asset_type', '-current_value'],
            },
        ),
    ]
