# Generated by Django 5.0.14 on 2026-02-16 23:39

import apps.intake.fields
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('intake', '0002_add_debt_classification'),
    ]

    operations = [
        migrations.CreateModel(
            name='FeeWaiverApplication',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('household_size', models.IntegerField(default=1, help_text='Number of people in household')),
                ('monthly_income', apps.intake.fields.EncryptedDecimalField(decimal_places=2, help_text='Total monthly income from all sources', max_digits=10)),
                ('monthly_expenses', apps.intake.fields.EncryptedDecimalField(decimal_places=2, help_text='Total monthly expenses', max_digits=10)),
                ('receives_public_benefits', models.BooleanField(default=False, help_text='Receives SSI, SNAP, TANF, or other means-tested benefits')),
                ('benefit_types', models.JSONField(blank=True, default=list, help_text="List of benefit programs (e.g., ['SNAP', 'Medicaid'])")),
                ('cannot_pay_full', models.BooleanField(default=True, help_text='Cannot pay $338 filing fee in full')),
                ('cannot_pay_installments', models.BooleanField(default=True, help_text='Cannot pay in 4 installments over 120 days')),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('approved', 'Approved'), ('denied', 'Denied')], default='pending', max_length=20)),
                ('filed_at', models.DateTimeField(blank=True, null=True)),
                ('decided_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('session', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='fee_waiver', to='intake.intakesession')),
            ],
            options={
                'db_table': 'fee_waiver_applications',
            },
        ),
    ]
