# Generated by Django 5.0.14 on 2026-02-17 00:07

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('intake', '0003_add_fee_waiver'),
    ]

    operations = [
        migrations.AlterField(
            model_name='feewaiverapplication',
            name='household_size',
            field=models.IntegerField(default=1, help_text='Number of people in household (must be at least 1)', validators=[django.core.validators.MinValueValidator(1)]),
        ),
        migrations.AlterField(
            model_name='feewaiverapplication',
            name='status',
            field=models.CharField(choices=[('pending', 'Pending'), ('approved', 'Approved'), ('denied', 'Denied')], db_index=True, default='pending', max_length=20),
        ),
    ]
