# Generated by Django 5.0.14 on 2026-05-16 05:02

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("documents", "0002_documenttype_creditor_bill"),
        ("intake", "0004_fix_fee_waiver_validation"),
    ]

    operations = [
        migrations.AddField(
            model_name="debtinfo",
            name="is_draft",
            field=models.BooleanField(
                default=False,
                help_text="True for entries auto-created from scanned documents, pending user confirmation",
            ),
        ),
        migrations.AddField(
            model_name="debtinfo",
            name="source_document",
            field=models.ForeignKey(
                blank=True,
                help_text="Document scan that generated this entry",
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="draft_debts",
                to="documents.uploadeddocument",
            ),
        ),
    ]
