# Generated by Django 5.0.14 on 2026-06-10 12:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("intake", "0005_debtinfo_draft_fields"),
    ]

    operations = [
        migrations.AddField(
            model_name="debtorinfo",
            name="filing_type",
            field=models.CharField(
                choices=[("individual", "Individual"), ("joint", "Joint")],
                default="individual",
                max_length=20,
            ),
        ),
        migrations.AddField(
            model_name="debtorinfo",
            name="household_size",
            field=models.PositiveIntegerField(default=1),
        ),
    ]
