# Generated by Django 5.0.14 on 2026-06-17 00:23

import django.db.models.deletion
from django.db import migrations, models

import apps.intake.fields


class Migration(migrations.Migration):

    dependencies = [
        ("intake", "0006_debtorinfo_filing_type_debtorinfo_household_size"),
    ]

    operations = [
        migrations.CreateModel(
            name="SOFAReport",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                ("has_prior_income", models.BooleanField(default=True)),
                ("has_creditor_payments", models.BooleanField(default=False)),
                ("has_business", models.BooleanField(default=False)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "session",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="sofa_report",
                        to="intake.intakesession",
                    ),
                ),
            ],
            options={
                "db_table": "sofa_reports",
            },
        ),
        migrations.CreateModel(
            name="SOFAPriorIncome",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                ("year", models.PositiveIntegerField()),
                (
                    "source",
                    models.CharField(help_text="e.g. Wages, Operating a business", max_length=255),
                ),
                (
                    "gross_amount",
                    apps.intake.fields.EncryptedDecimalField(decimal_places=2, max_digits=12),
                ),
                (
                    "report",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="prior_income",
                        to="intake.sofareport",
                    ),
                ),
            ],
            options={
                "db_table": "sofa_prior_income",
                "ordering": ["-year"],
            },
        ),
        migrations.CreateModel(
            name="SOFACreditorPayment",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                ("creditor_name", models.CharField(max_length=255)),
                (
                    "total_paid",
                    apps.intake.fields.EncryptedDecimalField(decimal_places=2, max_digits=12),
                ),
                ("dates_of_payments", models.CharField(blank=True, max_length=255)),
                (
                    "report",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="creditor_payments",
                        to="intake.sofareport",
                    ),
                ),
            ],
            options={
                "db_table": "sofa_creditor_payments",
            },
        ),
        migrations.CreateModel(
            name="FormAnswer",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                ("form_type", models.CharField(max_length=20)),
                ("field_key", models.CharField(max_length=100)),
                ("value", models.TextField(blank=True)),
                (
                    "session",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="form_answers",
                        to="intake.intakesession",
                    ),
                ),
            ],
            options={
                "db_table": "form_answers",
                "unique_together": {("session", "form_type", "field_key")},
            },
        ),
    ]
