# Generated by Django 5.0.14 on 2026-06-17 15:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("intake", "0007_sofareport_sofapriorincome_sofacreditorpayment_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="sofareport",
            name="has_prior_income",
            field=models.BooleanField(default=False),
        ),
    ]
