# Generated by Django 5.0.14 on 2026-06-18 01:48

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("intake", "0008_sofa_report_default_fix"),
    ]

    operations = [
        migrations.CreateModel(
            name="Codebtor",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                ("name", models.CharField(help_text="Full name of codebtor", max_length=255)),
                ("street_address", models.CharField(blank=True, max_length=255)),
                ("city", models.CharField(blank=True, max_length=100)),
                ("state", models.CharField(blank=True, max_length=2)),
                ("zip_code", models.CharField(blank=True, max_length=10)),
                (
                    "relationship",
                    models.CharField(
                        choices=[
                            ("spouse", "Spouse"),
                            ("former_spouse", "Former Spouse"),
                            ("relative", "Relative"),
                            ("friend", "Friend"),
                            ("business_partner", "Business Partner"),
                            ("other", "Other"),
                        ],
                        default="other",
                        max_length=20,
                    ),
                ),
                (
                    "session",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="codebtors",
                        to="intake.intakesession",
                    ),
                ),
            ],
            options={
                "db_table": "codebtors",
            },
        ),
        migrations.CreateModel(
            name="ExecutoryContract",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                (
                    "counterparty_name",
                    models.CharField(
                        help_text="Name of other party to the contract or lease", max_length=255
                    ),
                ),
                (
                    "contract_type",
                    models.CharField(
                        choices=[
                            ("lease", "Lease"),
                            ("contract", "Executory Contract"),
                            ("other", "Other"),
                        ],
                        default="contract",
                        max_length=20,
                    ),
                ),
                (
                    "description",
                    models.TextField(
                        blank=True, help_text="Brief description of the contract or lease"
                    ),
                ),
                (
                    "session",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="executory_contracts",
                        to="intake.intakesession",
                    ),
                ),
            ],
            options={
                "db_table": "executory_contracts",
            },
        ),
    ]
