# Generated by Django 5.0.14 on 2026-06-18 13:18

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("intake", "0009_add_executory_contracts_and_codebtors"),
    ]

    operations = [
        migrations.AddField(
            model_name="debtinfo",
            name="adversary_proceeding_needed",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="debtinfo",
            name="is_dischargeable",
            field=models.BooleanField(default=True),
        ),
        migrations.CreateModel(
            name="AdversaryProceeding",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                (
                    "proceeding_type",
                    models.CharField(
                        choices=[
                            ("student_loan", "Student Loan Discharge (§ 523(a)(8))"),
                            ("other", "Other Non-Dischargeable Debt"),
                        ],
                        max_length=20,
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("identified", "Identified"),
                            ("filed", "Filed"),
                            ("pending", "Pending"),
                            ("granted", "Granted"),
                            ("denied", "Denied"),
                            ("settled", "Settled"),
                        ],
                        default="identified",
                        max_length=20,
                    ),
                ),
                ("lender_name", models.CharField(blank=True, max_length=255)),
                (
                    "loan_amount",
                    models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True),
                ),
                ("loan_type", models.CharField(blank=True, max_length=50)),
                ("hardship_narrative", models.TextField(blank=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "debt",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        to="intake.debtinfo",
                    ),
                ),
                (
                    "session",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="adversary_proceedings",
                        to="intake.intakesession",
                    ),
                ),
            ],
            options={
                "db_table": "adversary_proceedings",
            },
        ),
    ]
